### ISSUE TITLE
updating to the letest version of whisper

### ISSUE THREAD

**Issue by Omer7731** [ssciwr/vink#41]
there is any way that you can share exact command to use pyinstaller how to compile this package that the command line will still working.  
if you interest I have personal project to complete and I'm planning to use whisper as a asr model. i can pay for it
please contact omerparhy@gmail.com if this is something that you interest.

**Comment by dokempf** [comment]
This repository contains all the packaging code for pyinstaller under an open license - please feel free to use accordingly. I do occasionally update the underlying version of whisper when I come around to do it. I am not interested in freelance work on this.

**Comment by dokempf** [comment]
For the issue on updating see #40
