### ISSUE TITLE
Linux script can't find run_whisper.py

### ISSUE THREAD

**Issue by markusbaker** [ssciwr/vink#43]
Following install instructions for linux:

```
sudo apt install ffmpeg python3 python3-pip git
git clone https://github.com/ssciwr/whisper-standalone.git
cd whisper-standalone
python -m pip install -r requirements.txt
python run_whisper.py
```

`[Errno 2] No such file or directory
`

All works well until the last line, can't find the file. Which is not surprising since the file is absent from the repo.

**Comment by dokempf** [comment]
Ups, this was renamed to `vink.py`. I will fix this as soon as I am vack on a PC.

**Comment by dokempf** [comment]
Fixed the documentation in `README`.
